StuDjango/StuDjango/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'', include('stuapp.urls', namespace='stuapp')),
]

StuDjango/stuapp/urls.py
#!/usr/bin/env python3
# coding=utf-8
# title          :urls.py
# description    :
# author         :JackieTsui
# organization   :pytoday.org
# date           :2017/9/7 6:33
# email          :jackietsui72@gmail.com
# notes          :
# ==================================================

# Import the module needed to run the script


from django.conf.urls import url
from stuapp import views


urlpatterns = [
    # main page
    url(r'^$', views.index, name='index'),
    # all topics
    url(r'^topics/$', views.topics, name='topics'),
    url(r'topics/(?P<topic_id>\d+)/$', views.topic, name='topic'),
    url(r'^new_topic/$', views.new_topic, name='new_topic'),
    url(r'^new_entry/(?P<topic_id>\d+)/$', views.new_entry, name='new_entry'),
    url(r'edit_entry/(?P<entry_id>\d+)/$', views.edit_entry, name='edit_entry'),
    url(r'.*', views.nothing, name='nothing')
]

StuDjango/users/urls.py
#!/usr/bin/env python3
# coding=utf-8
# title          :urls.py
# description    :user app url pattern
# author         :JackieTsui
# organization   :pytoday.org
# date           :2017/9/14 13:53
# email          :jackietsui72@gmail.com
# notes          :
# ==================================================

# Import the module needed to run the script
from django.conf.urls import url
from django.contrib.auth.views import login

from . import views


urlpatterns = [
    # login page
    url(r'^login/$', login, {'template_name': 'users/login.html'}, name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^register', views.register, name='register'),
]

StuDjango/stuapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Topic(models.Model):
    """Study title"""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.text


class Entry(models.Model):
    """Studied details about something."""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        """models returned formated by strings"""

        return self.text[:50] + "..."

StuDjango/users/models.py
from django.db import models

# Create your models here.

StuDjango/stuapp/forms.py
#!/usr/bin/env python3
# coding=utf-8
# title          :forms.py
# description    :TopicForms
# author         :JackieTsui
# organization   :pytoday.org
# date           :2017/9/12 19:52
# email          :jackietsui72@gmail.com
# notes          :
# ==================================================

# Import the module needed to run the script
from django import forms
from .models import Topic, Entry


class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

StuDjango/stuapp/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, Http404
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
# from django.shortcuts import HttpResponse

from .models import Topic, Entry
from .forms import TopicForm, EntryForm

# Create your views here.


def index(request):
    """django index page"""
    # return HttpResponse("Hello World for index.")
    return render(request, 'stuapp/index.html')


def topics(request):
    """all topics page"""
    topics = Topic.objects.order_by('date_added')
    # topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics': topics}
    return render(request, 'stuapp/topics.html', context)


def topic(request, topic_id):
    """show topic and entries"""
    try:
        topic = Topic.objects.get(id=topic_id)
    except Topic.DoesNotExist:
        return render(request, 'stuapp/404.html')
    # if topic.owner != request.user:
    #     raise Http404
    else:
        entries = topic.entry_set.order_by('-date_added')
        context = {'topic': topic, 'entries': entries, 'topic_id': topic_id}
        return render(request, 'stuapp/topic.html', context)


def nothing(request):
    """nothing here"""
    return render(request, 'stuapp/404.html')


@login_required
def new_topic(request):
    """add new topic"""
    if request.method != 'POST':
        # no commit data? create a new form
        form = TopicForm()
    else:
        # POST committed data, handle with data.
        form = TopicForm(request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            # form.save()
            return HttpResponseRedirect(reverse('stuapp:topics'))

    context = {'form': form}
    return render(request, 'stuapp/new_topic.html', context)


@login_required
def new_entry(request, topic_id):
    """add entries for topic"""
    try:
        topic = Topic.objects.get(id=topic_id)
    except Topic.DoesNotExist:
        return render(request, 'stuapp/404.html')
    if topic.owner != request.user:
        raise Http404

    if request.method != 'POST':
        # no commit data? create a entry form
        form = EntryForm()
    else:
        # POST committed data
        form = EntryForm(request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return HttpResponseRedirect(reverse('stuapp:topic', args=[topic_id]))

    context = {'topic': topic, 'form': form}
    return render(request, 'stuapp/new_entry.html', context)


@login_required
def edit_entry(request, entry_id):
    """edit entry"""
    try:
        entry = Entry.objects.get(id=entry_id)
    except Entry.DoesNotExist:
        return render(request, 'stuapp/404.html')
    topic = entry.topic
    if topic.owner != request.user:
        raise Http404

    if request.method != 'POST':
        form = EntryForm(instance=entry)
    else:
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('stuapp:topic', args=[topic.id]))

    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'stuapp/edit_entry.html', context)

StuDjango/users/views.py
from django.shortcuts import render, HttpResponse
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.conf import settings


# Create your views here.
def logout_view(request):
    """logout users"""
    logout(request)
    return HttpResponseRedirect(reverse('stuapp:index'))


def register(request):
    """register users"""
    if settings.REG:
        if request.method != 'POST':
            # no data post, create a empty form.
            form = UserCreationForm()
        else:
            # handle with posted data.
            form = UserCreationForm(data=request.POST)

            if form.is_valid():
                new_user = form.save()
                # let user auto login and redirect to index page.
                authenticated_user = authenticate(username=new_user.username, password=request.POST['password1'])
                login(request, authenticated_user)
                return HttpResponseRedirect(reverse('stuapp:index'))
        context = {'form': form}
        return render(request, 'users/register.html', context)
    else:
        return HttpResponse("Register Not Allowed Now!!!")

StuDjango/templates/stuapp/base.html
{% load bootstrap3 %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Pytoday Blog</title>
    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>
<body>
<!-- Static navbar -->
<nav class="container">
    <div class="container">
    <!-- <p><b><font color="#dc143c">app:stuapp--header</font></b></p> -->

        <div class="nav-header" >
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            </button>
            <a class="navbar-brand" href="{% url 'stuapp:index' %}">
                Pytoday Blog
            </a>
        </div>

        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'stuapp:topics' %}">Topics</a></li>
            </ul>

            <ul class="nav navbar=nav navbar-right">
                {% if user.is_authenticated %}
                    <li><a>Hello, {{ user.username }}.</a></li>
                    <li><a href="{% url 'users:logout' %}">logout</a></li>
                {% else %}
                    <li><a href="{% url 'users:login' %}">login</a></li>
                    <li><a href="{% url 'users:register' %}">register</a></li>
                {% endif %}
            </ul>
        </div>  <!--/.nav-collapse -->

    </div>
</nav>

    <div class="containner">

        <div class="page-header">
            {% block header %} {% endblock header %}
        </div>
        <div>
            {% block content %} {% endblock content %}
        </div>

    </div>
<!-- <p><b>foot....</b></p> -->
</body>
</html>

StuDjango/templates/stuapp/edit_entry.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>EditEntry</title>
</head>
<body>
{% extends "stuapp/base.html" %}
{% load bootstrap3 %}
{% block header %}
<h3>Edit entry:</h3>
{% endblock header %}

{% block content %}
    <h4><a href="{% url 'stuapp:topic' topic.id %}">Back to {{ topic }}</a></h4>
    <form action="{% url 'stuapp:edit_entry' entry.id %}" method="post" class="form">
        {% csrf_token %}
        <!-- {\{ form.as_p }} -->
        {% bootstrap_form form %}

        {% buttons %}
        <button name="submit" class="btn-primary">save change</button>
        {% endbuttons %}
    </form>
{% endblock content %}
</body>
</html>

StuDjango/templates/stuapp/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Django index page</title>
</head>
<body>
{% extends "stuapp/base.html" %}

{% block header %}
    <div class="jumbotron">
        <h1>Track you learning.</h1>
    </div>
{% endblock header %}

{% block content %}
    <h2>
    <a href="{% url 'users:register' %}">Register an account</a> to make your own Learning Log,
    and list the topics you are learning about.
    </h2>
    <h2>
        Whenever you learn something new about a topic, make an entry summarizing what you've learned.
    </h2>
{% endblock content %}
</body>
</html>

StuDjango/templates/stuapp/new_entry.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>New Entry</title>
</head>
<body>
{% extends "stuapp/base.html" %}
{% load bootstrap3 %}
{% block header %}
<h3>Add new entry</h3>
{% endblock header %}

{% block content %}
    <h4><a href="{% url 'stuapp:topic' topic.id %}">Back to {{ topic }}</a></h4>
    <form action="{% url 'stuapp:new_entry' topic.id %}" method="post" class="form">
        {% csrf_token %}
        <!-- {\{ form.as_p }} -->
        {% bootstrap_form form %}

        {% buttons %}
        <button name="submit" class="btn-primary">add entry</button>
        {% endbuttons %}
    </form>
{% endblock content %}

</body>
</html>

StuDjango/templates/stuapp/new_topic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>New Topic</title>
</head>
<body>
{% extends "stuapp/base.html" %}
{% load bootstrap3 %}

{% block header %}
    <h2>Add a new topic:</h2>
{% endblock header %}

{% block content %}
    <form action="{% url 'stuapp:new_topic' %}" method="post" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}

        {% buttons %}
        <button name="submit" class="btn-primary">add topic</button>
        {% endbuttons %}
    </form>
{% endblock content %}
</body>
</html>

StuDjango/templates/stuapp/topic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Topic Details</title>
</head>
<body>
{% extends "stuapp/base.html" %}
{% block header %}
    <h2>{{ topic }}</h2>
{% endblock header %}

{% block content %}
    <h4><a href="{% url 'stuapp:new_entry' topic.id %}">add new entry</a></h4>

    {% for entry in entries %}
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4>
                    {{ entry.date_added|date:'M d, Y H:i' }}
                    <small>
                        <a href="{% url 'stuapp:edit_entry' entry.id %}">edit entry</a>
                    </small>
                </h4>
            </div>
            <div class="panel-body">
                {{ entry.text | linebreaks }}
            </div>
        </div>  <!-- panel -->
     {% empty %}
        No entry here for topic id: {{ topic_id }}
    {% endfor %}

    <h4><a href="{% url 'stuapp:new_entry' topic.id %}">add new entry</a></h4>
{% endblock content %}
</body>
</html>

StuDjango/templates/stuapp/topics.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Topics</title>
</head>
<body>
{% extends "stuapp/base.html" %}
{% block header %}
<h1>Topics</h1>
{% endblock header %}

{% block content %}
    <h3><a href="{% url 'stuapp:new_topic' %}">Add a new topic:</a></h3>
    <ul>
        {% for topic in topics %}
            <li>
                <h3><a href="{% url 'stuapp:topic' topic.id %}">{{ topic }}</a></h3>
            </li>
        {% empty %}
        <li>No topics have been added yet.</li>
        {% endfor %}
    </ul>
     <h3><a href="{% url 'stuapp:new_topic' %}">Add a new topic:</a></h3>

{% endblock content %}
</body>
</html>

StuDjango/templates/users/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
</head>
<body>
{% extends "stuapp/base.html" %}
{% load bootstrap3 %}

{% block header %}
    <h2>Login to your account.</h2>
{% endblock header %}

{% block content %}
<!--
    {\% if form.errors %}
    <h3>Your username and password didn't match. Please try again.</h3>
    {\% endif %}
-->

    <form method="post" action="{% url 'users:login' %}" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}

    {% buttons %}
    <button name="submit">login</button>
    {% endbuttons %}
    <input type="hidden" name="next" value="{% url 'stuapp:index' %}" />
    </form>
{% endblock content %}

</body>
</html>

StuDjango/templates/users/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Register</title>
</head>
<body>
{% extends "stuapp/base.html" %}
{% block content %}
    <form method="post" action="{% url 'users:register' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">register</button>
    <input type="hidden" name="next" value="{% url 'stuapp:index' %}" />
    </form>
{% endblock content %}
</body>
</html>